workspace:
  base: /go/src
  path: github.com/tungsheng/go-hook

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  backend:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - make fmt-check
      # - make gtfmt-check
      - make misspell-check
      - make test-vendor

  generate:
    image: golang:1.11
    pull: true
    group: build
    commands:
      - cp env/env.drone .env
      - make generate

  test:
    image: golang:1.11
    pull: true
    group: testing
    commands:
      - make test

  build:
    image: golang:1.11
    pull: true
    group: testing
    commands:
      - make docker_build
      - make tar

  # deploy to staging, listen master branch
  scp_dev:
    image: appleboy/drone-scp
    pull: true
    host: dev.fullinn.tw
    port: 22
    username: deploy
    target: /home/deploy/drone/${DRONE_REPO}
    secrets:
      - source: deploy_key
        target: scp_key
    source:
      - release.tar.gz
    when:
      branch: master
      local: false

  ssh_dev:
    image: appleboy/drone-ssh
    pull: true
    host: dev.fullinn.tw
    port: 22
    username: deploy
    command_timeout: 120
    secrets:
      - source: deploy_key
        target: ssh_key
    script:
      - rm -rf ${DRONE_REPO} && mkdir -p ${DRONE_REPO}
      - tar -zxmf /home/deploy/drone/${DRONE_REPO}/release.tar.gz -C ${DRONE_REPO}
      - cd ${DRONE_REPO} && make dev
    when:
      branch: master
      local: false

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
