workspace:
  base: /go/src
  path: github.com/tungsheng/go-hook

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  # deploy to staging, listen master branch
  scp_dev:
    image: appleboy/drone-scp
    pull: true
    host: hook.tonka.sh
    port: 22
    username: deploy
    command_timeout: 120
    target: /home/deploy/drone-github/${DRONE_REPO}
    secrets:
      - source: deploy_key
        target: scp_key
    source:
      - release.tar.gz
    when:
      branch: master
      local: false

  ssh_dev:
    image: appleboy/drone-ssh
    pull: true
    host: hook.tonka.sh
    port: 22
    username: deploy
    command_timeout: 120
    secrets:
      - source: deploy_key
        target: ssh_key
    script:
      - rm -rf ${DRONE_REPO} && mkdir -p ${DRONE_REPO}
      - tar -zxmf /home/deploy/drone-github/${DRONE_REPO}/release.tar.gz -C ${DRONE_REPO}
      - cd ${DRONE_REPO} && docker-compose up
    when:
      branch: master
      local: false


  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
